name: Teams Notification

on:
  pull_request:
    types:
      - opened
      - synchronize

jobs:
  notification:
    uses: cloud-development-team/.github/.github/workflows/teams-notification.yaml
    inputs:
      # How to use: https://github.com/toko-bifrost/ms-teams-deploy-card/tree/master/#usage
      custom_actions: |
        - text: View Pull Request
          url: ${{ github.event.pull_request.html_url }}
    secrets:
      WEBHOOK_URI: ${{ secrets.WEBHOOK_URI }}
