name: Commit Lint

on:
  pull_request:
    types:
      - opened
      - synchronize
    branches:
      - main
      - release
      - production

jobs:
  lint:
    runs-on: ubuntu-latest
    name: check commit messages
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Checkout lint config file
        uses: actions/checkout@v3
        with:
          repository: htaic/.github
          path: github-configs
          ref: main

      - name: Override package.json
        run: |
          mv -f github-configs/.github/files/commitlint/package.json .

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install dependencies
        run: |
          npm install

      - name: Create commitlint.config.js
        run: |
          echo "module.exports = {extends: ['@commitlint/config-conventional']}" > commitlint.config.js

      - name: Validate commits
        run: |
          npx commitlint --from ${{ github.event.pull_request.base.sha }} --verbose
