name: CloudAI  Deploy
run-name: CloudAI Deploy - ${{ inputs.release_env }}

permissions: write-all

on:
  workflow_call:
    inputs:
      release_env:
        description: 'Release Environment'
        required: true
        default: ""
        type: string
      release_version:
        description: 'Release Version'
        required: true
        default: ""
        type: string
      backend_repo:
        description: 'backend Repo'
        required: true
        default: ""
        type: string
      target_branch:
          description: 'Target Branch'
          required: true
          default: ""
          type: string
      target_version:
          description: 'Target Version'
          required: false
          default: ""
          type: string




jobs:     
  build-and-deploy-to-s3-qa:
    name: Build and push artifact to s3(QA)
    if: ${{ inputs.target_branch == 'release' }}
    uses: ./.github/workflows/job_cloudai_qa_deploy.yaml
    with:
      release_env: ${{ inputs.release_env }}
      backend_repo: ${{ inputs.backend_repo }}
      release_version: ${{ inputs.release_version }}
    secrets: inherit
  build-and-deploy-to-s3-prod:
    name: Build and push artifact to s3(PROD)
    if: ${{ inputs.target_branch == 'production' }}
    uses: ./.github/workflows/job_cloudai_prod_deploy.yaml
    with:
      release_env: ${{ inputs.release_env }}
      backend_repo: ${{ inputs.backend_repo }}
      release_version: ${{ inputs.release_version }}
      target_version: ${{ inputs.target_version }}
    secrets: inherit