name: SightMind Frontend Deploy
run-name: SightMind Frontend Deploy - ${{ inputs.release_env }}

permissions: write-all

on:
  workflow_call:
    outputs:
      version:
        description: "Version number from semver"
        value: ${{ jobs.pnpm-build.outputs.version }}
    inputs:
      working_dir:
        required: false
        description: "Operating path for path dependent steps"
        type: string
        default: .
      node_versions:
        required: false
        description: "List of node version which want to scan"
        type: string
        default: "['20.14.0']" #"['18.16']"
      release_env:
        description: 'Release Environment'
        required: true
        default: ""
        type: string
      frontend_repo:
        description: 'Frontend Repo'
        required: true
        default: ""
        type: string
      target_branch:
          description: 'Target Branch'
          required: true
          default: ""
          type: string

jobs:
  detect-changes:
    name: Detect SightMind changes
    runs-on: ubuntu-latest
    environment: sm_${{ inputs.target_branch }}
    outputs:
      sightmind: ${{ steps.filter.outputs.sightmind }}
      sightmind_minor: ${{ steps.filter.outputs.sightmind_minor }}  
    steps:
      
      - name: Checkout
        uses: actions/checkout@v4
        with:
          repository: cloud-development-team/${{ inputs.frontend_repo }}
          ref: refs/heads/${{ inputs.target_branch}}
          token: ${{ secrets.GH_MANAGEPACKAGE_TOKEN }}

      - name: Filtering changed repository
        uses: dorny/paths-filter@v2
        id: filter
        with:
          base: ${{ inputs.target_branch }}
          filters: |
            sightmind:
              - './apps/sightmind/**'
            sightmind_minor:
              - './apps/sightmind_minor/**'

  statitic-analysis:
    name: Analysis code quality
    if: ${{ needs.detect-changes.outputs.sightmind == 'true' && inputs.target_branch == 'release' }}
    uses: ./.github/workflows/static-analysis.yaml
    needs: detect-changes
    with:
      REPO_NAME: hc-frontend-mono
      BUILD_PATH: apps/sightmind
      QUALITY_REPORT: true
      STREAM: sightmind-hc-frontend-mono
    secrets: inherit
  
  statitic-analysis-minor:
    name: Analysis code quality
    if: ${{ needs.detect-changes.outputs.sightmind_minor == 'true' && inputs.target_branch == 'release' }}
    uses: ./.github/workflows/static-analysis.yaml
    needs: detect-changes
    with:
      REPO_NAME: hc-frontend-mono
      BUILD_PATH: apps/sightmind_minor
      QUALITY_REPORT: true
      STREAM: sightmind-hc-frontend-mono
    secrets: inherit

  build-and-release:
    name: Build and release
    if: ${{ inputs.target_branch == 'production' && needs.detect-changes.outputs.sightmind_minor == 'true' }}
    needs: detect-changes
    uses: ./.github/workflows/job_sm_pnpm_build.yaml
    with:
      working_dir: ./apps/sightmind
      release_env: ${{ inputs.release_env }}
      frontend_repo: ${{ inputs.frontend_repo }}
      target_branch: ${{ inputs.target_branch }}
    secrets: inherit

  build-and-release-minor:
    name: Build and release(minor)
    if: ${{ inputs.target_branch != 'production' }}
    # if: ${{ needs.detect-changes.outputs.sightmind_minor == 'true' && inputs.target_branch != 'production' }}
    needs: detect-changes
    uses: ./.github/workflows/job_sm_pnpm_build.yaml
    with:
      working_dir: ./apps/sightmind_minor
      release_env: ${{ inputs.release_env }}
      frontend_repo: ${{ inputs.frontend_repo }}
      target_branch: ${{ inputs.target_branch }}
    secrets: inherit