name: SightMind Backend Deploy
run-name: SightMind Backend Deploy - ${{ inputs.release_env }}

permissions: write-all

on:
  workflow_call:
    outputs:
      version:
        description: "Version number from semver"
        value: ${{ jobs.pnpm-build.outputs.version }}
    inputs:
      working_dir:
        required: false
        description: "Operating path for path dependent steps"
        type: string
        default: .
      node_versions:
        required: false
        description: "List of node version which want to scan"
        type: string
        default: "['20.14.0']" #"['18.16']"
      release_env:
        description: 'Release Environment'
        required: true
        default: ""
        type: string
      release_version:
        description: 'Release Version'
        required: true
        default: ""
        type: string
      backend_repo:
        description: 'backend Repo'
        required: true
        default: ""
        type: string
      target_branch:
          description: 'Target Branch'
          required: true
          default: ""
          type: string
      target_version:
          description: 'Target Version'
          required: false
          default: ""
          type: string

jobs:
  detect-changes:
    name: Detect SightMind changes
    runs-on: ubuntu-latest
    if: ${{ inputs.target_branch != 'production' }}
    outputs:
      sightmind: ${{ steps.filter.outputs.sightmind }}
      sightmind_minor: ${{ steps.filter.outputs.sightmind_minor }}  
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with: 
          repository: cloud-development-team/${{ inputs.backend_repo }}
          ref: refs/heads/${{ inputs.target_branch}}
          token: ${{ secrets.AUTOMATION_GH_MANAGEPACKAGE_TOKEN }}

      - name: Filtering changed repository
        uses: dorny/paths-filter@v3
        id: filter
        with:
          base: ${{ inputs.target_branch }}
          filters: |
            sightmind:
              - './apps/**'
            sightmind_minor:
              - './apps-old/**'
              
  static-analysis:
    name: Analysis code quality
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.sightmind == 'true' && inputs.target_branch == 'release' }}
    uses: cloud-development-team/.github/.github/workflows/static-analysis.yaml@main
    with:
      REPO_NAME: sightmind-backend-mono
      BUILD_PATH: apps
      QUALITY_REPORT: true
    secrets: inherit

  static-analysis-minor:
    name: Analysis code quality
    needs: detect-changes
    if: ${{ needs.detect-changes.outputs.sightmind_minor == 'true' && inputs.target_branch == 'release' }}
    uses: cloud-development-team/.github/.github/workflows/static-analysis.yaml@main
    with:
      REPO_NAME: sightmind-backend-mono
      BUILD_PATH: apps-old
      QUALITY_REPORT: true
    secrets: inherit

  build-and-push-to-s3:
    name: Build and push artifact to s3
    needs: detect-changes
    # if: ${{ needs.detect-changes.outputs.sightmind == 'true' || inputs.target_version == 'major' || inputs.release_version == 'hotfix' }}
    if: ${{ inputs.target_version == 'major' || inputs.release_version == 'hotfix' || inputs.target_version == 'both'}}
    uses: ./.github/workflows/job_sm_backend_build.yaml
    with:
      working_dir: ./
      version: major
      release_env: ${{ inputs.release_env }}
      backend_repo: ${{ inputs.backend_repo }}
      target_branch: ${{ inputs.target_branch }}
      release_version: ${{ inputs.release_version }}
      target_version: ${{ inputs.target_version }}
    secrets: inherit

  build-and-push-to-s3-minor:
    name: Build and push artifact to s3 (minor)
    needs: detect-changes
    # if: ${{ needs.detect-changes.outputs.sightmind_minor == 'true' || inputs.target_version == 'minor'}}
    if: ${{ inputs.target_version == 'minor' || inputs.target_version == 'both' }}
    uses: ./.github/workflows/job_sm_backend_build.yaml
    with:
      working_dir: ./
      version: minor
      release_env: ${{ inputs.release_env }}
      backend_repo: ${{ inputs.backend_repo }}
      target_branch: ${{ inputs.target_branch }}
      release_version: ${{ inputs.release_version }}
    secrets: inherit