name: SightMind Frontend Deploy
run-name: SightMind Frontend Deploy - ${{ inputs.release_env }}

permissions: write-all

on:
  workflow_call:
    outputs:
      version:
        description: "Version number from semver"
        value: ${{ jobs.pnpm-build.outputs.version }}
    inputs:
      working_dir:
        required: false
        description: "Operating path for path dependent steps"
        type: string
        default: .
      node_versions:
        required: false
        description: "List of node version which want to scan"
        type: string
        default: "['20.14.0']" #"['18.16']"
      release_env:
        description: 'Release Environment'
        required: true
        default: ""
        type: string
      release_version:
        description: 'Release Version'
        required: true
        default: ""
        type: string
      frontend_repo:
        description: 'Frontend Repo'
        required: true
        default: ""
        type: string
      target_branch:
          description: 'Target Branch'
          required: true
          default: ""
          type: string
      target_version:
          description: 'Target Version'
          required: false
          default: ""
          type: string

jobs:
  build-and-release:
    name: Build and release
    if: ${{ inputs.target_version == 'major' || inputs.release_version == 'hotfix' || inputs.target_version == 'both'}}
    uses: ./.github/workflows/job_sm_frontend_build.yaml
    with:
      working_dir: ./apps/sightmind
      version: major
      release_env: ${{ inputs.release_env }}
      frontend_repo: ${{ inputs.frontend_repo }}
      target_branch: ${{ inputs.target_branch }}
      release_version: ${{ inputs.release_version }}
      target_version: ${{ inputs.target_version }}
    secrets: inherit

  build-and-release-minor:
    name: Build and release(minor)
    if: ${{ inputs.target_version == 'minor' || inputs.target_version == 'both'}}
    uses: ./.github/workflows/job_sm_frontend_build.yaml
    with:
      working_dir: ./apps/sightmind_minor
      version: minor
      release_env: ${{ inputs.release_env }}
      frontend_repo: ${{ inputs.frontend_repo }}
      target_branch: ${{ inputs.target_branch }}
      release_version: ${{ inputs.release_version }}
      target_version: ${{ inputs.target_version }}
    secrets: inherit