name: CloudAI PROD Build Deploy
run-name: CloudAI PROD Build Deploy - ${{ inputs.release_env }}

permissions: write-all

on:
  workflow_call:
    inputs:
      release_env:
        description: 'Release Environment'
        required: true
        default: ""
        type: string
      release_version:
        description: 'Release Version'
        required: true
        default: ""
        type: string
      backend_repo:
        description: 'backend Repo'
        required: true
        default: ""
        type: string
      target_version:
          description: 'Target Version'
          required: false
          default: ""
          type: string


env:
  CODEFREEZE: ${{ secrets.CODEFREEZE }}
  GH_PAT_AUTOMATION: ${{ secrets.GH_PAT_AUTOMATION_SEMANTIC_RELEASE }}

jobs:     
  copy-src-folder-from-qa-to-prod:
    runs-on: ubuntu-latest

    steps:
      # --- AWS 자격 증명 구성
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::224792116665:role/role-duclo-qa-github-ci
          role-session-name: GitHub-Actions-Assume
          aws-region: us-east-1

    
      - name: Copy source files from S3
        run: |
          aws s3 cp s3://duclo-build-q-ue1/src/${{ inputs.target_version }}/ .

      - name: ReConfigure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::619071312308:role/role-wc025-prod-github-ci
          role-session-name: GitHub-Actions-Assume
          aws-region: us-east-1
      - name: Copy source files to S3
        run: |
          aws s3 sync . s3://wc025-build-p-ue1/src/${{ inputs.release_version }}/
  copy-venv-file-from-qa-to-prod:
    runs-on: ubuntu-latest

    steps:
      # --- AWS 자격 증명 구성
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::224792116665:role/role-duclo-qa-github-ci
          role-session-name: GitHub-Actions-Assume
          aws-region: us-east-1

    
      - name: Copy source files from S3
        run: |
          aws s3 cp s3://duclo-build-q-ue1/venv/${{ inputs.target_version }}/venv.tar.zst  .

      - name: ReConfigure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::619071312308:role/role-wc025-prod-github-ci
          role-session-name: GitHub-Actions-Assume
          aws-region: us-east-1
      - name: Copy source files from S3
        run: |
          aws s3 sync venv.tar.zst s3://wc025-build-p-ue1/venv/${{ inputs.release_version }}/venv.tar.zst


  make-zip-file:
    runs-on: ubuntu-latest
    needs: build-and-deploy-to-s3
    steps:
      - uses: actions/checkout@v4
        with:
          repository: duclo/oncloud-wiseai-service
          ref: refs/heads/develop
          token: ${{ secrets.DUCLO_GH_MANAGEPACKAGE_TOKEN }}
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: arn:aws:iam::619071312308:role/role-wc025-prod-github-ci
          role-session-name: GitHub-Actions-Assume
          aws-region: us-east-1
      - name: zip file 
        run: |
          sync_script="aws s3 sync s3://wc025-build-p-ue1/src/${{ inputs.release_version }}/ ."
          cp_script="aws s3 cp s3://wc025-build-p-ue1/venv/${{ inputs.release_version }}/venv.tar.zst - | tar --zstd --strip-components=1 -xpf -"
          sed -i "/^aws s3 cp/ s@.*@${cp_script}@" ./codedeploy/deploy.sh
          sed -i "/^aws s3 sync/ s@.*@${sync_script}@" ./codedeploy/deploy.sh
          cat ./codedeploy/deploy.sh
          zip -r deploy.zip appspec.yml codedeploy
          aws s3 cp deploy.zip s3://wc025-build-p-ue1/cloudai/deploy.zip --metadata version=${{ inputs.release_version }}
