name: Manual Analysis

run-name: 'manual-analysis'

on:
  workflow_dispatch:
    inputs:
      REPO_NAME:
        description: 'Name of repository'
        required: true
        type: string
        default: 'Insert Repo Name'
      BRANCH:
        description: 'Target Branch'
        required: true
        type: string
        default: 'release'
      BUILD_PATH:
        description: 'Build target path under repository'
        required: true
        type: string
        default: '.'
      QUALITY_REPORT:
        description: 'Make static analysis result report'
        required: false
        type: boolean
        default: true

      # CIM_SERVER:
      #   description: 'Domain of cim server'
      #   required: false
      #   type: string
      #   default: "cim.kdoggy.systems"
      # DEPLOY:
      #   required: false
      #   type: string
      #   default: 'release'
      # STREAM:
      #   required: false
      #   type: string
      #   default: 'Insert Coverity Stream(Project) Name'

jobs:
  static-analysis:
    name: Analysis code quality
    uses: cloud-development-team/.github/.github/workflows/static-analysis.yaml@main
    with:
      DEPLOY: ${{ inputs.DEPLOY }}
      REPO_NAME: ${{ inputs.REPO_NAME }}
      BUILD_PATH: ${{ inputs.BUILD_PATH }}
      QUALITY_REPORT: ${{ inputs.QUALITY_REPORT }}
    secrets: inherit