name: Deploy Template

on:
  workflow_call:
    inputs:
      environment:
        type: string
        description: environment to deploy to
        required: true
    secrets:
      GH_MANAGEPACKAGE_TOKEN:
        required: true

jobs:
  deploy:
    name: Test env ${{ inputs.environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.environment }}
    
    steps:
    - name: Dump env
      run: |
        echo GH_MANAGEPACKAGE_TOKEN is $GH_MANAGEPACKAGE_TOKEN
        if [[ $GH_MANAGEPACKAGE_TOKEN == *"123"* ]]; then
          echo "This is the 123!"
        else
          echo "This is NOT NOT NOT 123!"
        fi
      env:
        GH_MANAGEPACKAGE_TOKEN: ${{ secrets.GH_MANAGEPACKAGE_TOKEN }}
